name: Hello
on:
  push:
    branch:
      - master
jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: ls -la
      - run: npm install
      - run: npm run build


  deploy:

